runtime: nodejs18
instance_class: F1
env_variables:
  REACT_APP_url: 'https://young-exclusive-back.rj.r.appspot.com/'
  GENERATE_SOURCEMAP: false

handlers:
- url: /static
  static_dir: build/static

- url: /favicon.ico
  static_files: build/favicon.ico
  upload: build/favicon.ico

- url: /logo192.png
  static_files: build/logo192.png
  upload: build/logo192.png

- url: /logo512.png
  static_files: build/logo512.png
  upload: build/logo512.png

- url: /manifest.json
  static_files: build/manifest.json
  upload: build/manifest.json

- url: /.*
  static_files: build/index.html
  upload: build/index.html
